echo "We are trying this practical from linux EC2"
echo "We are from batch-24 and learning git/gihub"
echo "Happy weekend"
echo "Hello Guys, it's me Darshan"
echo "Good Morning!"
echo "This is the new line"
echo "Adding data from branc1 to master barnch"
echo "Hello all!"
echo "This is branch1"
